### ISSUE TITLE
[BUG-01] MonthlyGoal 조회 시, 다른 사람의 게시물이 보이는 이슈.

### ISSUE THREAD

**Issue by devjun10** [dailyge/dailyge-server#149]
## 📝 연관 PR
- https://github.com/dailyge/dailyge-server/pull/132
- https://github.com/dailyge/dailyge-server/pull/146 - hotfix

<br/><br/>

## ❓ 작성 이유

월간 목표를 조회할 때, **`자신이 등록한 글이 아닌데도 다른 사람이 조회 가능한 장애가 발생`** 했습니다. 이 과정에서 **`어떻게 대처했는지`**, **`앞으로 어떻게 대응할 지`** 에 대해 정리하기 위해 글을 작성하게 되었습니다. 

<br/><br/>

## 📝 내용

전체 순서는 다음과 같습니다.

1. 장애 감지
2. 장애 전파
3. 장애 대응
4. 왜 발생했을까?
5. 배운점
6. 앞으로는 어떻게 해야할까?

<br/><br/><br/><br/>

## 1. 장애 감지

2024.09.11. **16시 20분** 경, 실 서버에 버그가 발생했다는 내용을 전달 받았습니다. 서비스 초기라 기능도, API도 몇 개 없는데, 어떤 장애가 발생했는지 불안하면서도 궁금했습니다.

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbkqEEk%2FbtsJyKsZEUG%2F8yzHgGccMBs1FzKE1Cugf0%2Fimg.png)

<br/><br/><br/><br/>

살펴보니, 월간 일정표에서 **`이달의 목표`** 를 등록할 수 있는데, 본인이 작성한 목표가 아니어도 조회가 되는 이슈였습니다. 즉, 다른 사용자가 작성한 목표를 조회할 수 있었던 거죠.

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FXyhFg%2FbtsJz0A80fe%2FmsJbHJZnkKbMt1YuLKrgm1%2Fimg.png)

<br/><br/><br/><br/>

원인을 살펴보니 조회할 때, 검색 조건에 사용자 PK를 사용하지 않고, 게시글 PK로만 조회해서 다른 사용자의 정보가 조회되던 것이었습니다.

```java
@Repository
@RequiredArgsConstructor
public class MonthlyGoalReadDao implements MonthlyGoalEntityReadRepository {

    private final JPAQueryFactory queryFactory;

    ......

    // 사용자 PK를 사용하지 않고, PK로만 조회
    public List<MonthlyGoalJpaEntity> findMonthlyGoalsByCursor(final Cursor cursor) {
        return queryFactory.selectFrom(monthlyGoalJpaEntity)
            .where(
                monthlyGoalJpaEntity.id.gt(cursor.getIndex())
                    .and(monthlyGoalJpaEntity.deleted.eq(false))
            )
            .limit(cursor.getLimit())
            .fetch();
    }
}
```

<br/><br/><br/><br/>

## 2. 장애 전파

우선 어떤 장애가 발생했는지 장애를 전파 했습니다. 16시 20분 경에 버그를 감지하고, 16시 22분 경에 전파가 이루어졌습니다. 원인은 파악 됐지만 롤백을 먼저 하지 않은 이유는 **`안정적인 이전 버전`** 이 없었기 때문입니다.

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FpYpnG%2FbtsJz3klgbD%2Fl3mzJYmQ97zah1r7mmKaLK%2Fimg.png)

<br/><br/><br/><br/>

## 3. 장애 대응

hotfix 브랜치를 딴 후, 아래와 같이 사용자 PK를 검색 조건에 추가해주었습니다. 이후 [v1.0.1](https://github.com/dailyge/dailyge-server/releases/tag/v1.0.0)(from [v1.0.0](https://github.com/dailyge/dailyge-server/releases/tag/v1.0.1)) 버전을 재 배포 했습니다. 

```java
@Repository
@RequiredArgsConstructor
public class MonthlyGoalReadDao implements MonthlyGoalEntityReadRepository {

    private final JPAQueryFactory queryFactory;

    ......

    // 사용자 PK를 사용하지 않고, PK로만 조회
    public List<MonthlyGoalJpaEntity> findMonthlyGoalsByCursor(final Cursor cursor) {
        return queryFactory.selectFrom(monthlyGoalJpaEntity)
            .where(
                monthlyGoalJpaEntity.id.gt(cursor.getIndex())
                    .and(monthlyGoalJpaEntity.userId.eq(userId))     // 조건 추가
                    .and(monthlyGoalJpaEntity.deleted.eq(false))
            )
            .limit(cursor.getLimit())
            .fetch();
    }
}
```

<br/><br/><br/><br/>

재 배포 후, 모든 버그가 사라진 시간은 16시 40분 입니다. 즉, 장애 감지부터 해결까지 **`약 20분`** 정도가 걸렸습니다. 배포 시간이 조금 걸렸는데, 현재 프로젝트에서는 테라폼을 사용하고 있기 때문에, **`배포 중에도 인프라를 동적으로 제어`** 할 수 있습니다. 이 부분을 간과해 대응이 늦었습니다.

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbKprom%2FbtsJxXl2s0l%2FhoLHkfX8LTckr2RnteAQmK%2Fimg.png)

> 테라폼으로 로드 밸런서 설정만 변경 했다면, 최소 6분 이상 단축시킬 수 있었는데 이 부분이 미흡했습니다. 

<br/><br/><br/><br/>

## 4. 왜 발생했을까?

**`관습적 코드 작성`**, **`QA를 하고 있다는 그 자체에 대한 안도감`** 두 가지로 볼 수 있을 것 같습니다. 

1. 관습적 코드 작성
2. QA를 하고 있다는 그 자체에 대한 안도감

<br/>

먼저 프로젝트에 익숙해지며 **`관습적으로 코드를 작성`** 했고, 이 과정에서 자신의 게시글만 보인다는 조건이 빠진 줄도 모르고 있었습니다. 익숙하고 안정감을 느끼는 순간이 제일 위험한 데도요. 또한 개발 서버에서 QA를 진행하고 있었기 때문에, **`QA를 한다는 자체에 너무 마음을 놓고`** 있었습니다. QA의 진짜 목적은 **`다양한 시나리오를 가정하고 버그를 잡는 것`** 인데, 기능이 잘 동작하면 다양한 엣지 케이스를 찾기보다 안도했던 것 같습니다.

> 어쩌면 QA 역량 부족으로 볼 수도 있을 것 같네요.

<br/><br/><br/><br/>

## 5. 배운점

**`QA 역량 강화 및 공유`**, **`장애가 발생했을 때, 프로세스 확립`**, **`장애 전파`** 의 필요성에 대해 배울 수 있었습니다. 

1. QA 역량 강화 및 공유: 최대한 다양한 시나리오를 가정하고, 기능이 추가되면 이를 문서로 남겨 팀원들과 공유하는 것의 중요성. 나만의 QA 노하우(?) 습득.
2. 장애가 발생했을 때 프로세스 확립: 장애가 나면 문제를 파악 후, 최선의 방법을 **주저 없이** 실행할 수 있는 프로세스 확립.
3. 장애 전파: 어떤 경로든 버그를 제보 받고, 다른 사람들에게 빠르게 전파할 수 있는 경로 확보.

<br/><br/><br/><br/>

## 6. 앞으로는 어떻게 해야할까?

**`커밋 전, 셀프 리뷰`** 와 **`코드 리뷰 강화`**, **`QA 역량 강화`** 가 필요할 것 같습니다. 이 부분은 회의에서 충분한 대화가 이루어졌기 때문에 간략히 적겠습니다. 특히 코드 리뷰에 대해 조금 길게 이야기 했는데, Discussion을 열어 이 부분은 정리해두겠습니다.

1. 커밋 전, 셀프 리뷰
4. 코드 리뷰 강화
5. QA 역량 강화

[DLG-220]: https://jungjunwoojun.atlassian.net/browse/DLG-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DLG-279]: https://jungjunwoojun.atlassian.net/browse/DLG-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kmularise** [comment]
이번 기회로 코드 리뷰를 좀 더 꼼꼼히 하면서 버그도 미리 잡아내고, QA를 통해서 dev 서버에서 충분히 테스트되면 좋을 것 같다는 생각을 하게 된거 같아요! 버그 정리해주셔서 감사합니다!

**Comment by beatmeJY** [comment]
장애가 발생했을때 얼마만큼 빠르게 대처하느냐가 중요한데 약 20분만에 아주 빠르게 대처가 되어서 좋았던 것 같습니다. 이렇게 글 또한 잘 정리해주시고 팀원들에게 전파해주셔서 감사합니다!
