### ISSUE TITLE
[BUG-02] 중복 된 Logged-In Cookie가 동시에 존재하는 이슈.

### ISSUE THREAD

**Issue by beatmeJY** [dailyge/dailyge-server#168]
## 📝 연관 PR
- https://github.com/dailyge/dailyge-server/pull/151

<br/><br/>

## ❓ 작성 이유
실제 운영 환경에서 동일한 이름의 쿠키가 동시에 존재하는 상황이 발생하여 이에 대한 문제상황과 해결 방법을 공유하기 위해 작성하였습니다.

<br/><br/>

## 📝 내용

전체 순서는 다음과 같습니다.

1. 장애 감지
2. 장애 전파
3. 장애 대응
4. 왜 발생했을까?
5. 배운점
6. 앞으로는 어떻게 해야할까?

<br/><br/><br/><br/>

## 1. 장애 감지

2024.09.13. **20시 24분** 경, 실제 운영환경에 최신 코드를 반영하고 테스트 차 확인하다가 발견하게 되었습니다.

![image](https://github.com/user-attachments/assets/f643a9f8-a91a-4a06-a583-b0f7a09df65d)

우리 서비스는 브라우저에서 위의 사진에서 처럼 로그인 여부를 체크하는 `Logged_In` 이라는 쿠키를 사용 중 이였는데, 이 값이 **두 개**가 존재하는 버그를 발견하게 되었습니다.

<br/><br/><br/><br/>

## 2. 장애 전파
우선 팀원 내 인프라를 담당해주시는 @devjun10님과 실시간으로 같이 확인하고 있었기에 빠르게 이전 버전(정상 버전)으로 롤백해주셨고, 곧바로 다른 팀원분께도 전파해 주셔서 저는 빠르게 버그에만 집중할 수 있도록 해주셨습니다.

<br/><br/><br/><br/>

## 3. 장애 대응
팀원분의 도움으로 인해 운영환경은 빠르게 정상화 되어 아주 급하게 수정을 해야하는 것은 아니였지만, 
스스로 실수를 했다는 사실에 당황했던 부분과 다른 이슈인 `403 에러`와도 겹쳐져서 약 1시간이 지난 **21시 34분**에 dev 반영 후 테스트하였고, **21시 48분**에 prod에 정상적으로 반영이 완료되었습니다.

<br/><br/><br/><br/>

## 4. 왜 발생했을까?
문제 상황을 보면 `Logged-In`의 `domain`정보가 다른 것을 확인을 할 수 있었습니다.
이유는 서버에서 보내준 쿠키와 클라이언트에서 값을 변경한 쿠키의 도메인 정보가 일치하지 않아 결과적으로 **2개**가 생성이 된 것 입니다.

**서버 측 코드**
```java
private static final String ROOT_DOMAIN = ".dailyge.com";

public static String createResponseCookie(
  final String name,
  final String value,
  final String path,
  final long maxAge,
  final boolean httpOnly,
  final String env
) {
    if (!"local".equals(env)) {
        final ResponseCookie cookie = ResponseCookie.from(name, value)
            .domain(ROOT_DOMAIN)
            .path(path)
            .httpOnly(httpOnly)
            .secure(true)
            .maxAge(maxAge)
            .build();
        return cookie.toString();
    }
...
}
```

**클라이언트 측 문제 코드**
```javascript
const handleLogout = async () => {
    try {
        Cookies.set("Logged-In", "no");
        ...
    }
    ...
}
```

이는 정상적인 상황에선 로그아웃 시 서버에서 모든 쿠키를 무효화해 주지만, 만약 실패하더라도 클라이언트에서 `Logged-In`쿠키의 값을 `no`로 변경해 로그아웃을 정상적으로 처리를 해주기 위한 과정에서 실수 했던 문제였습니다.

이를 해결하기 위해선 서버에서 보내준 쿠키의 설정과 `domain`, `secure` 등을 모두 동일하게 설정하여 수정해야 하는데, 이럴 경우에는 수정보다 삭제하는 것이 더 편리하고 합리적이여서 `Logged-In` 쿠키 자체를 삭제하도록 변경하여 문제를 해결하였습니다.

**클라이언트 수정 코드**
```javascript
const handleLogout = async () => {
    try {
        Cookies.remove("Logged-In");
        ...
    }
    ...
}
```

<br/><br/><br/><br/>

## 5. 배운점
저는 백엔드 개발자이기도 하지만, 이 프로젝트에서 만큼은 클라이언트 개발자이기도 하였습니다. 
따라서 프론트엔드 코드를 잘 알지 못하더라도 더 책임감을 가지고 스스로 좀 더 신경을 써서 알아보며 구현했어야 하는데, 근거 없는 자신감으로 다른 블로그 글을 찾아보지 않고 쿠키를 세팅해주었던 것이 실수였다는 것을 깨닫고 반성하게 되었습니다.

<br/><br/><br/><br/>

## 6. 앞으로는 어떻게 해야할까?
그리고 이번에 결과적으로 버그를 낸 가장 큰 요인은 `local` 환경에서 테스트를 많이 하고 잘 동작한다고 오인했던 것이라고 생각합니다.

`local`환경에선 쿠키를 이용한 **서브도메인을 테스트 해볼 수 없는데** 로컬에서 열심히 테스트를 진행했고, `dev`환경에서는 로그아웃을 한 번 실행하여 잘 동작하여 개발자 도구를 켜보지 못했던 것이 잘못 되었던 것 같습니다.

따라서
 - 클라이언트(관심이 적은 분야)의 코드이더라도 조금 더 책임감을 가지도록 함.
 - 로컬 환경 테스트도 나쁘지는 않지만 실제 환경과 가장 비슷한 dev에서 더 열심히 QA를 진행해야 함.

다음부터는 위와 같은 마음가짐을 잘 가지고 진행해야 할 것 같습니다.

**Comment by devjun10** [comment]
수고하셨어요 ㅎㅎ

**Comment by devjun10** [comment]
QA 역량도 중요할 것 같은데, 추석에 서점 가보니까 아래와 같은 책들이 있더라고요. 부트캠프 QA편 구매해서 읽고 있는데, 재밌네요. 시간나면 한 번 읽어보셔요.

- [부트캠프 QA편](https://product.kyobobook.co.kr/detail/S000213447437)
- [QA 엔지니어](https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000005619604)
- [더 괜찮은 QA가 되기 위한 프랙티컬 테스트 자동화](https://product.kyobobook.co.kr/detail/S000001019656)

**Comment by beatmeJY** [comment]
ㅎㅎ 좋네요 해당 버그 발생 당시 도와주셔서 감사드리고 추천 서적까지 찾아주시고 감사합니다!!👍🏻
